import {it,expect} from 'vitest';
import {spawnSync} from 'node:child_process';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
const script=resolve('scripts/push-reviewed.ps1');
function git(cwd:string,args:string[]){const r=spawnSync('git',args,{cwd,encoding:'utf8',windowsHide:true});if(r.status!==0)throw new Error(`Fixture Git failed: ${args[0]}`);return r.stdout;}
function fixture(){const root=mkdtempSync(join(tmpdir(),'hera-publish-test-'));const cwd=join(root,'heraAgent');mkdirSync(cwd);git(cwd,['init','--initial-branch=main']);git(cwd,['config','user.name','Fixture']);git(cwd,['config','user.email','fixture@example.invalid']);return {root,cwd};}
it('bootstrap refuses an unrelated parent repository before any remote work',()=>{const {cwd}=fixture();const nested=join(cwd,'heraAgent');mkdirSync(nested);const result=spawnSync('pwsh',['-NoProfile','-File',script,'-Message','fixture'],{cwd:nested,encoding:'utf8',windowsHide:true});expect(result.status).not.toBe(0);expect(result.stderr).toContain('Wrong repository root');expect(git(cwd,['remote','-v'])).toBe('');});
it('wrong origin is blocked with a fake authenticated GitHub CLI, without network mutation',()=>{const {root,cwd}=fixture();const fake=join(root,'tools');mkdirSync(fake);writeFileSync(join(fake,'gh.ps1'),`if ($args[0] -eq 'api') { 'NotNull92' } else { '{"name":"heraAgent","nameWithOwner":"NotNull92/heraAgent","isPrivate":false,"url":"https://github.com/NotNull92/heraAgent","defaultBranchRef":{"name":"main"}}' }; $global:LASTEXITCODE=0\n`);git(cwd,['remote','add','origin','https://example.invalid/unrelated.git']);const env={...process.env};const pathKey=Object.keys(env).find(k=>k.toLowerCase()==='path')??'PATH';env[pathKey]=fake+(process.platform==='win32'?';':':')+(env[pathKey]??'');const result=spawnSync('pwsh',['-NoProfile','-File',script,'-Message','fixture'],{cwd,env,encoding:'utf8',windowsHide:true});expect(result.status).not.toBe(0);expect(result.stderr).toContain('Unexpected origin destination');expect(git(cwd,['remote','get-url','origin']).trim()).toBe('https://example.invalid/unrelated.git');});
it('source scanner catches a tracked auth file despite a later ignore rule',()=>{const {cwd}=fixture();writeFileSync(join(cwd,'auth.json'),'{}');git(cwd,['add','auth.json']);git(cwd,['commit','-m','fixture']);writeFileSync(join(cwd,'.gitignore'),'auth.json\n');const result=spawnSync(process.execPath,[resolve('scripts/check-source.mjs')],{cwd,encoding:'utf8',windowsHide:true});expect(result.status).not.toBe(0);expect(result.stderr).toContain('Sensitive tracked path');});
