import {it,expect} from 'vitest';
import {mkdtemp,writeFile,symlink} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {acquireWorkspace} from '../src/session/workspace-lock.js';
import {PhasePolicy,baseline,validateProposalPath} from '../src/session/phase-policy.js';
it('locks a canonical workspace and never steals stale/incomplete locks',async()=>{const home=await mkdtemp(join(tmpdir(),'hera-lock-'));const lock=await acquireWorkspace(home,home);await expect(acquireWorkspace(home,home)).rejects.toMatchObject({exitCode:6});await lock.release();const next=await acquireWorkspace(home,home);await writeFile(join(next.directory,'owner.json'),'{}');await expect(next.release()).rejects.toMatchObject({errorCode:'LOCK_OWNERSHIP_CHANGED'});await expect(acquireWorkspace(home,home)).rejects.toMatchObject({exitCode:6});});
it('rejects pending workers, changed baseline and missing native safety evidence',()=>{for(const state of [{workers:1},{approvals:1},{commands:1},{turnActive:true},{baselineMatches:false}]){const policy=new PhasePolicy();policy.analyze();expect(()=>policy.quiesce({workers:0,commands:0,approvals:0,turnActive:false,baselineMatches:true,...state})).toThrow();}const policy=new PhasePolicy();policy.analyze();policy.quiesce({workers:0,commands:0,approvals:0,turnActive:false,baselineMatches:true});expect(()=>policy.apply(true,{readOnly:false,spawnDisabled:false,resumePolicy:false})).toThrow('verified');});
it('detects external edits and rejects traversal/junction patches',async()=>{const cwd=await mkdtemp(join(tmpdir(),'hera-baseline-'));await writeFile(join(cwd,'file.txt'),'a');const before=await baseline(cwd);await writeFile(join(cwd,'file.txt'),'b');expect(await baseline(cwd)).not.toBe(before);await expect(validateProposalPath(cwd,'../escape')).rejects.toThrow();const outside=await mkdtemp(join(tmpdir(),'hera-outside-'));await symlink(outside,join(cwd,'link'),process.platform==='win32'?'junction':'dir');await expect(validateProposalPath(cwd,'link/change')).rejects.toThrow('Symlink');});
