import React,{useEffect,useState} from 'react';
import {Box,Text,useApp,useStdout} from 'ink';
import type {InteractiveSession} from '../session/interactive.js';
import {ProviderKeyInput,ProviderLogin} from './ProviderInput.js';
import {Composer} from './Composer.js';
import {ApplyReview} from './ApplyReview.js';
import {SettingsPicker} from './SettingsPicker.js';
import {safeText} from '../errors.js';
export function App({session}:{session:InteractiveSession}){
  const [,update]=useState(0);const {exit}=useApp();const {stdout}=useStdout();
  useEffect(()=>{let dirty=false;const changed=()=>{dirty=true;};const quit=()=>exit();session.on('change',changed);session.on('quit',quit);stdout.on('resize',changed);const timer=setInterval(()=>{if(dirty){dirty=false;update(n=>n+1);}},50);return()=>{clearInterval(timer);session.off('change',changed);session.off('quit',quit);stdout.off('resize',changed);};},[session,exit,stdout]);
  const ko=session.config.language==='ko';const width='columns'in stdout&&typeof stdout.columns==='number'?stdout.columns:80;const height='rows'in stdout&&typeof stdout.rows==='number'?stdout.rows:24;const rows=Math.max(4,height-9);const transcript=session.transcript.split('\n').slice(-rows).join('\n').slice(-12000);
  return <Box flexDirection="column"><Text bold>HERA · {safeText(session.cwd)}</Text><Text>{ko?'모드':'Mode'}: GPT · {ko?'단계':'Phase'}: {session.controller?.phase.phase??'IDLE'} · {session.status}</Text><Text>{ko?'요청 모델':'Requested model'}: {safeText(session.config.main.model??(ko?'선택 필요':'unselected'))} · effort: {session.config.main.reasoningEffort??'default'} · Codex 0.160.1</Text>{width>=65&&<Text>{session.controller?.collaborationEnabled?(ko?"워커: "+String(session.controller.workers?.activeCount??0)+" 활성 / 상한 "+session.config.workers.maxConcurrent+" · 적용: 검토 승인 필요":"Workers: "+String(session.controller.workers?.activeCount??0)+" active / limit "+session.config.workers.maxConcurrent+" · Apply: review required"):(ko?'워커 검증: /doctor · 적용: 검토 승인 필요 · 사용량: 알 수 없음':'Worker verification: /doctor · Apply: review required · Quota: unknown')}</Text>}<Text>{safeText(session.approval)||(ko?'대기 중인 승인 없음 · /help 도움말':'No approval pending · /help')}</Text>{session.providerKeyInput?<ProviderKeyInput language={session.config.language} save={key=>{void session.saveProviderKey(key);}} cancel={()=>session.cancelProviderKey()}/>:session.providerLoginText?<ProviderLogin text={session.providerLoginText} cancel={()=>{void session.interrupt();}} quit={()=>{void session.close().finally(()=>exit());}}/>:session.controller?.review&&!session.busy?<ApplyReview key={session.controller.review.id} review={session.controller.review} rows={Math.max(8,height-6)} columns={width} language={session.config.language} approve={()=>{void session.approveApply();}} cancel={()=>session.cancelApply()}/>:session.selection?<SettingsPicker key={session.selection.title} menu={session.selection} language={session.config.language} rows={Math.max(7,height-6)} choose={value=>{void session.selectOption(value);}} cancel={()=>session.cancelSelection()} quit={()=>{void session.close().finally(()=>exit());}}/>:<><Box borderStyle="single" flexDirection="column" height={Math.max(5,rows)} overflow="hidden"><Text>{safeText(transcript)||(ko?'Hera 전용 로그인과 모델을 설정하세요. /doctor로 상태를 확인합니다.':'Configure Hera login and model selection. /doctor shows readiness.')}</Text></Box><Composer language={session.config.language} busy={session.busy} send={text=>{void session.submit(text);}} cancel={()=>{void session.interrupt().catch(e=>session.add(String(e)));}} quit={()=>{void session.close().finally(()=>exit());}}/></>}</Box>;
}
